\c chess
DROP OWNED BY FIDE_OFFICIAL;
DROP OWNED BY PLAYER;
DROP OWNED BY TOURNAMENT_OFFICIAL;
DROP OWNED BY ENGINE;

DROP USER FIDE_OFFICIAL;
DROP USER PLAYER;
DROP USER TOURNAMENT_OFFICIAL;
DROP USER ENGINE;

CREATE USER FIDE_OFFICIAL;
CREATE USER PLAYER;
CREATE USER TOURNAMENT_OFFICIAL;
CREATE USER ENGINE;

GRANT SELECT ON Federation, Player, Year TO FIDE_OFFICIAL;
GRANT SELECT ON Federation, Player, Year, Tournament, Game, Position, Opening, Endgame, Next_legal_moves, Reached, Year TO PLAYER;
GRANT SELECT ON Tournament, Game, Year TO TOURNAMENT_OFFICIAL;
GRANT SELECT ON Game, Position, Opening, Endgame, Next_legal_moves, Reached TO ENGINE;

GRANT UPDATE (Rating, Belongs_to) ON Player TO FIDE_OFFICIAL;
GRANT UPDATE (Won_by) ON Tournament TO TOURNAMENT_OFFICIAL;
GRANT UPDATE (Won, Played_black, Played_white) ON Game TO TOURNAMENT_OFFICIAL;
GRANT UPDATE (Eval) ON Position TO ENGINE;
GRANT UPDATE (Evaluation, Next_best_move) ON Endgame TO ENGINE;

GRANT INSERT ON Federation, Player TO FIDE_OFFICIAL;
GRANT INSERT ON Game, Position, Opening TO PLAYER;
GRANT INSERT ON Tournament, Game TO TOURNAMENT_OFFICIAL;
GRANT INSERT ON Opening, Endgame, Next_legal_moves, Reached TO ENGINE;

GRANT DELETE ON Federation, Player TO FIDE_OFFICIAL;
GRANT DELETE ON Game, Position, Opening TO PLAYER;
GRANT DELETE ON Tournament, Game TO TOURNAMENT_OFFICIAL;
GRANT DELETE ON Opening, Endgame, Next_legal_moves, Reached TO ENGINE;
